### ISSUE TITLE
llnl_lustre_ost plugin not working correctly

### ISSUE THREAD

**Issue by wooloo1121** [LLNL/ldms-plugins-llnl#4]
Hi,

We installed the llnl_lustre_ost plugin on one of our oss nodes. But with ldms_ls, for the first time it will show the instances with some random words and blank lines, as follows
hwoss1/sjtu-OST0000/1977118
hwoss1/sjtu-OST0000/1977106
hwoss1/sjtu-OST0000/1975483
hwoss1/sjtu-OST0000/1973539
hwoss1/sjtu-OST0000/1930998
hwoss1/sjtu-OST0000//lustre/home/ac.3595
hwoss1/sjtu-OST0000
Y
7
2

Then it will only return the following error
first_line   : 0
last line    : 0
first column : 6
last column  : 9
str           : syntax error, unexpected DQUOTED_STRING_T, expecting ',' or '}'
Error 1 looking up the metric set directory.

What might be the problem? 
Thank you and look forward to your reply.

**Comment by morrone** [comment]
I am going to guess that there is a problem in the jobstats parsing. 

Oh, wow. I made a really stupid cut-and-paste error that likely explains this.

FYI, even we aren't using the llnl_lustre_[ost|mdt] plugins anywhere yet because ldms 4.3.4 from last Friday is the first one that will really support metric sets dynamically appearing and disappearing. But I hope to have us start using them soon. So thank you for the bug report! This is really helpful.

I will fix that and release 1.6 today. I will let you know when that happens.

**Comment by morrone** [comment]
Correction, lets make it version 1.7. Try the 1.7 release and let me know if that addresses the issue that you are seeing:

https://github.com/LLNL/ldms-plugins-llnl/releases/tag/1.7

**Comment by morrone** [comment]
Double correction, use 1.8. I shouldn't try to multi-task.

https://github.com/LLNL/ldms-plugins-llnl/releases/tag/1.8

**Comment by wooloo1121** [comment]
@morrone Thank you so much, it works correctly now.
