### ISSUE TITLE
the samplers may "get stuck" 

### ISSUE THREAD

**Issue by wooloo1121** [LLNL/ldms-plugins-llnl#6]
Hi,

We deployed the ost job stats sampler on our oss servers and notice some problems. 

At some point, the sampler side of ldms "gets stuck" and stop getting data of newly submitted jobs. If we restart ldms sampler side, the data are starting to be collected again.

For most jobs (even jobs running for hours), there is only one record in the database for each ost that they have I/O on. The sampling frequency is every 60s, and the aggregator collecting frequency is higher than that.

We are not sure if these are problems of the sampler plugins. But could you help do some checking? Thank you so much and look forward to your reply.

**Comment by morrone** [comment]
What version of ldms are you using?

How did you confirm that the sampler side was the problem? Did you use ldms_ls to confirm its data was remaining static?

**Comment by wooloo1121** [comment]
@morrone It's ldms 4.3.4 (somewhere between 4.3.4-beta and 4.3.4 newest release). The data of new jobs started to show up only when we restarted the sampler side, restarting the aggregator or the database did not do anything helpful. 

Sorry we did not notice if the data of old jobs were remaining static (and they might be static since the jobs might be finished), just the very obvious situation was that the jobs started since the beginning of a new day were not showing up with ldms_ls. We checked lustre job stats and the job data was indeed there. So finally we restarted the sampler side and the jobs started to show up.

**Comment by wooloo1121** [comment]
We think it is a memory issue, so I close this for now and will post further updates if we notice more problems and have different opinions.

**Comment by wooloo1121** [comment]
Hi @morrone, this issue still remains. We found that as ldms sampler side runs (with this ost job stats sampler), the number of jobs collected becomes smaller than the number of jobs existing in lustre job stats files, newly submitted jobs are not getting collected while data of old jobs are still being updated, which are confirmed with ldms_ls and data stored in the database. When we restart the sampler side, a lot more jobs show up in ldms_ls (but the number of jobs will get smaller as ldms runs). 

We still think that it might be a problem of memory, just not one that could be solved by adding the memory allocated to ldms daemon. I'm guessing that the memory management of ldms might be blamed, old jobs disappeared but the memory are not used by new jobs. Please let me know if you have other opinions.

**Comment by morrone** [comment]
Is there anything useful in the ldmsd log? Do you see an error that says "ost_job_stats_data_create failed"?

**Comment by morrone** [comment]
Also, can you tell me roughly how many jobs are still seen when you notice that new jobs are not appearing?

**Comment by wooloo1121** [comment]
@morrone yes there are many errors saying "ost_job_stats_data_create failed". 

Around 1400 jobs are seen in ldms_ls on one oss server while the number gets to over 40000 after restarting. And the error still exists after restarting.

**Comment by morrone** [comment]
Wow! 40000 on a single daemon is probably stressing LDMS's design. But if we get that to work, we'll know we are in good shape.

There are three ways that ost_job_stats_data_crreate(). The first two are simple malloc type failures. My guess is that this is not the problem, or there would likely be many more issues than you are seeing. Check and see how much of the memory on your system the ldmsd is using. If the system has plenty of memory left, we can probably assume that is not the issue. But I can always add more information to the error message if that is suspect.

The third possibility is that the call to ldms_set_new() is failing, and that is a call in the upstream ldms code.

How much memory are you telling the ldmsd to preallocate with the -m option (or the equivalent environment variable)?

Have you upgraded to the real 4.3.4 release? I would recommend doing that.

Do you have ldms aggregators set up to collect data from the ldmsds on the oss nodes? Are the aggregators also upgraded to 4.3.4?

How many nodes does each aggregator collect information from?

You might try upgrading to the recent 4.3.5 release of ovis-ldms. But I am not sure that will help.

I mention versions of the aggregators because even if I am correctly calling ldms_set_delete() in the ost plugin, under the covers the ldmsd may not free all of the resources for the metric sets that are no longer needed until all of the remote connections (from the aggregators, most likely) to that data set are closed. 4.3.4 was the first release in which the sampler would tell the remote connections that they needed to close. Previously the memory would just stay around forever even when a plugin called the function to delete it.

I need to double check my own code in the plugin to make sure that I didn't make a mistake somewhere in the accounting. I will try to get to that early next week (it is the holiday season around here so my availability will be lower than normal).

But if my code is correct, then there may be an upstream bug still remaining in this area.

Here is what I would do if I were you: make sure that you are using some large -m number for sampler nodes. And make sure the the memory setting for the aggregator nodes is that number times the number of sampler nodes from which it collects. But that may be a prohibitively large memory value on the aggregator...

We might also take a look at whether your jobid settings are reasonable. Do you really have 40000 separate jobs talking to this oss in the job_stats caching window?  It is certainly possible, I just want to rule out the possibility that the jobid string is being set incorrectly on your system and resulting in more entries in the job_stats flie then their should be.

You might also consider shrinking the caching window to limit the number of entries in the job_stats file. Of course this could mean that a long running job that only writes intermittently over periods longer than the cache window will disappear and reappear in the job_stats flie. That might cause some consternation downstream since the counters will reset and need to be aggregated back together somewhere later in the data collection pipeline.

**Comment by wooloo1121** [comment]
@morrone Thank you so much for this detailed explanation. 

> There are three ways that ost_job_stats_data_crreate(). The first two are simple malloc type failures. My guess is that this is not the problem, or there would likely be many more issues than you are seeing. Check and see how much of the memory on your system the ldmsd is using. If the system has plenty of memory left, we can probably assume that is not the issue. But I can always add more information to the error message if that is suspect.

I checked with top command, the ldms sampler is only taking a very small part of the memory on the system (0.1%) and there are plenty of memory left.

> How much memory are you telling the ldmsd to preallocate with the -m option (or the equivalent environment variable)?

For the sampler, it was 128M and we made it to 512M yesterday when restarting. For the aggregator, it is 7G.

> Have you upgraded to the real 4.3.4 release? I would recommend doing that.
Do you have ldms aggregators set up to collect data from the ldmsds on the oss nodes? Are the aggregators also upgraded to 4.3.4?
How many nodes does each aggregator collect information from?

Yes we have an aggregator set up to collect data from the oss nodes, but it is only one aggregator vs. all 10 oss nodes. (I guess we should have more aggregators) The samplers are upgraded to the real 4.3.4 release, while the aggregator hasn't reach that yet, it is around 4.3.4 beta somewhere and we will do the upgrading.

> Here is what I would do if I were you: make sure that you are using some large -m number for sampler nodes. And make sure the the memory setting for the aggregator nodes is that number times the number of sampler nodes from which it collects. But that may be a prohibitively large memory value on the aggregator...

Yeah thanks for this suggestion, we would certainly do it.

> We might also take a look at whether your jobid settings are reasonable. Do you really have 40000 separate jobs talking to this oss in the job_stats caching window? It is certainly possible, I just want to rule out the possibility that the jobid string is being set incorrectly on your system and resulting in more entries in the job_stats flie then their should be.

For this, we have the jobid_var of lustre on all the oss nodes set to SLURM_JOB_ID (we use slurm scheduler on our cluster). But there are still some jobs in lustre job stats files with names of some other kind of string. I haven't figure out why this happens yet.

Thank you in advance for double checking your code :) Have a good holiday!

**Comment by wooloo1121** [comment]
> Around 1400 jobs are seen in ldms_ls on one oss server while the number gets to over 40000 after restarting. And the error still exists after restarting.

Sorry the 1400 and 40000 are numbers of total records shown by ldms_ls. Since we have 18 osts on each oss sever and each ost has its own records of every job doing read/write on it, there are multiple records for every job. The number of different jobs is a few thousand.

**Comment by morrone** [comment]
Your memory settings for sampler and aggregator nodes sounds pretty reasonable to me.  And one aggregator for 10 samplers would normally be just fine (one aggregator could normally collect from many more sampler nodes). But with these very high metric set counts, we are getting into areas where my might need to tap the ldms experts upstream.

In ovis-hpc/ovis#564 I learned that the sampler ldmsd may (if clients don't reply to the notification that the metric set has been deleted) keep the metric sets around for a full 10 minutes by default. That seems like an excessively long time to me.

I would also try setting the environment variable LDMS_DELETE_TIMEOUT to 30 in the sampler ldmsd's environment when starts. If that makes a difference, that might let me off the hook. :) But I'll still plan to review my code early next week.

**Comment by wooloo1121** [comment]
Hi @morrone, we tried with LDMS_DELETE_TIMEOUT set to 30, this doesn't seem to work and the errors still exist. But upgrading the aggregator does make a difference, we deployed a very recent version (newer than the 4.3.4 release, for the reason that it is the version in our forked repository which contains timescaledb store plugin) and there have been no errors since then! We will let it run for a few days and see if there is still anything wrong. Thank you!

**Comment by wooloo1121** [comment]
@morrone Did you consider spaces in jobids when you parse them? It looks like the sampler will only get the part before the first space in the actual job id, and this may cause some create failure when multiple jobs have the same "first part".

**Comment by morrone** [comment]
That could be. I will check on that.

**Comment by morrone** [comment]
I broke out the jobid parsing issue into #10.

**Comment by wooloo1121** [comment]
Hi @morrone, this problem seems to be fixed in 4.3.4 release. Thank you for your help and patience!
